print("##############################")
print("#                            #")
print("#    Anggraeni Dwi Zahra     #")
print("#       2410817220018        #")
print("#                            #")
print("##############################")