nama = input("Masukkan Nama: ")
nim = input("Masukkan NIM: ")
kelas_paralel = input("Masukkan Kelas Paralel: ")
ttl = input("Masukkan Tempat/Tanggal Lahir: ")
alamat = input ("Masukkan Alamat: ")
hobby = input("Masukkan Hobby: ")
no_hp = input("Masukkan No. HP : ")

print("Nama: " + nama)
print("NIM: " + nim)
print("Kelas Paralel: " + kelas_paralel)
print("Tempat/Tanggal Lahir: " + ttl)
print("Alamat: " + alamat)
print("Hobby: " + hobby)
print("No.HP: " + no_hp)